version: "3.8"
services:
  redis:
    image: "redis:6.2-alpine"
    container_name: vaadin_dynamic_navbar_redis
    command: /bin/sh -c "redis-server --requirepass password"
    ports:
      - "6380:6379"